primary:
  - "Did not even care."
  - "Completely unmoved."
  - "Zero interest detected."
  - "Total apathy achieved."
  - "Utterly indifferent."
  - "Not a single care."
  - "Perfectly unbothered."
  - "No reaction whatsoever."
  - "Emotionless since forever."
  - "Care level: absolute zero."

secondary:
  - "Not even worth a raised eyebrow."
  - "Humanity just collectively shrugged."
  - "Nobody flinched, not even once."
  - "A record-breaking wave of indifference."
  - "This barely registered on the care scale."
  - "Nothing to see here, folks."
  - "Public reaction: a resounding meh."
  - "Entirely ignored, just as expected."
  - "No hearts or minds were moved."
  - "The crowd didn’t even blink."

footnote:
  - "Proudly ignored by everyone."
  - "Another milestone in not caring."
  - "Approved by the apathy council."
  - "Made with 100% disinterest."
  - "Certified care-free."
  - "Fueled by collective boredom."
  - "Officially irrelevant since day one."
  - "Powered by the indifference engine."
  - "Backed by nobody in particular."
  - "Supported by zero enthusiasm."
