base:
  title: "WhoCares.io"
  description: "Professional Silence Tracker"
  url: "https://whocares.io"

server:
  port: 8080
  host: ""

app: 
  seed: 8000000
  refresh_interval: 5000
  cache_duration: 30000

static:
  messages_dir: "assets/messages"
  fonts_dir: "/Users/quentin/projects/whocares/assets/fonts"
  public_dir: "public"